### ISSUE TITLE
Contracts

### ISSUE THREAD

**Issue by kevinlun** [StrongJoshua/Water-World#44]
MainFXApplication.createAccount(String first, String last, String username, String password, Authorization accountType)

**Comment by StrongJoshua** [comment]
MainFXApplication.logout() lol

**Comment by Rajminster** [comment]
updateUserInfo()

**Comment by beaumitch** [comment]
addWaterPurityReport(WaterSource source, WaterPurityCondition condition, double virusPPM,
double contaminant PPM, String submitterName, Date reportDate): WaterPurityReport

**Comment by gnoziere** [comment]
MainFXApplication.setMapLocation(WaterLocation location): void
