### ISSUE TITLE
JUnits

### ISSUE THREAD

**Issue by gnoziere** [StrongJoshua/Water-World#45]
Please post the method you will be working on for JUnit testing.

**Comment by gnoziere** [comment]
WaterPurityReportController handleSubmitPressed() method

**Comment by gnoziere** [comment]
WaterLocation.java getContinent() method

**Comment by beaumitch** [comment]
WaterSourceReport::getPurityReportsByMonth() method

**Comment by kevinlun** [comment]
WaterSourceReport::getPurityReportsByYear() method
